{% set python_min = "3.10" %}
{% set name = "pointpats" %}
{% set version = "2.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pointpats-{{ version }}.tar.gz
  sha256: 8134f4bf46f2ccd40da026706c163a78a12abced4cee7c5a4648d76ec56c6ea6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - libpysal >=4.8.0
    - matplotlib-base >=3.6
    - numpy >=1.24
    - pandas
    - python >={{ python_min }}
    - scipy >=1.10
    - shapely >=2.0
    - geopandas >0.12

test:
  requires:
    - python {{ python_min }}
  imports:
    - pointpats
  # conda-forge does not have an opencv-contrib-python package yet
  # and it looks like an optional dependency here.
  # See https://github.com/pysal/pointpats/pull/82
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Statistical analysis of planar point patterns.

  description: |
    This pointpats package is intended to support the statistical analysis
    of planar point patterns.
  doc_url: https://pointpats.readthedocs.io/en/latest/
  dev_url: https://github.com/pysal/pointpats

extra:
  recipe-maintainers:
    - weikang9009
    - slumnitz
    - martinfleis
    - knaaptime
    - jGaboardi
